/*
 * viz.js — hand-built inline SVG for the three views.
 *
 * Palette is fixed by the brief: pin = dark red nominal circle over a light red
 * tolerance band; hole = dark blue nominal circle over a light blue band.
 */
var Viz = (function () {
  'use strict';

  var C = {
    pinDark: '#a01722', pinLight: 'rgba(214, 69, 84, 0.34)', pinEdge: '#d64554',
    holeDark: '#123a8f', holeLight: 'rgba(58, 110, 214, 0.34)', holeEdge: '#3a6ed6',
    overlap: 'rgba(122, 46, 138, 0.40)'
  };

  function fmt(v, dp) {
    if (dp === undefined) dp = 1;
    var s = Math.abs(v) < 0.05 ? (0).toFixed(dp) : v.toFixed(dp);
    // Strip a trailing ".0" so integers read cleanly.
    s = s.replace(/\.0+$/, '');
    return s;
  }
  function signed(v, dp) {
    var s = fmt(Math.abs(v), dp);
    if (Math.abs(v) < 0.005) return '0';
    return (v > 0 ? '+' : '−') + s;
  }
  function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  /** A "nice" axis step at or above the requested raw step. */
  function niceStep(raw) {
    if (!(raw > 0)) return 1;
    var mag = Math.pow(10, Math.floor(Math.log(raw) / Math.LN10));
    var cands = [1, 2, 2.5, 5, 10].map(function (m) { return m * mag; });
    for (var i = 0; i < cands.length; i++) {
      if (cands[i] >= raw) return cands[i];
    }
    return 10 * mag;
  }

  /**
   * Decimals an axis label needs for a given step. Without this a 2.5 um step
   * printed at 0 dp reads as "-3, 0, +3, +5, +8" -- uniform spacing carrying a
   * sequence that looks broken.
   */
  function tickDecimals(step) {
    if (step >= 1) return (step % 1 === 0) ? 0 : 1;
    return Math.min(3, Math.ceil(-Math.log(step) / Math.LN10) + 1);
  }

  /** Tick values across [lo, hi], generated by index so they cannot drift. */
  function ticks(lo, hi, targetCount) {
    var step = niceStep((hi - lo) / targetCount);
    var first = Math.ceil(lo / step);
    var out = [];
    for (var i = first; i * step <= hi + step * 1e-9; i++) out.push(i * step);
    return { values: out, step: step, dp: tickDecimals(step) };
  }

  /** Annulus drawn as a stroked circle -- avoids fill-rule subtleties. */
  function ring(cx, cy, rIn, rOut, fill) {
    var w = rOut - rIn;
    if (w <= 0.01) return '';
    var r = (rIn + rOut) / 2;
    return '<circle cx="' + cx + '" cy="' + cy + '" r="' + r.toFixed(2) +
           '" fill="none" stroke="' + fill + '" stroke-width="' + w.toFixed(2) + '"/>';
  }

  /* ------------------------------------------------------------ 1. circle view */

  /*
   * The basic circle's placement buys headroom in both directions. Interference
   * letters push INWARD (at 25 mm a U7 hole sits 62 um below basic) and clearance
   * letters push OUTWARD (E7 reaches 61 um above it), so the space either side is
   * balanced rather than centred: 90 px in, 88 px out.
   */
  var R0 = 104;          // displayed radius of the basic size, px
  var R_MIN = 14;        // innermost radius we will draw, px
  var R_MAX = 192;       // outermost radius that still fits the 400 px box, px

  /**
   * The drawing scale, pinned per diameter.
   *
   * A +/-3 um band on a 3 mm circle is 0.1% of the diameter -- at true scale it is
   * a hairline -- so the bands have to be exaggerated, and the view is only honest
   * if the factor is computed, shown and adjustable.
   *
   * Crucially the factor is derived from the DIAMETER alone, via the widest
   * deviations reachable in the precision grades (see precisionExtremes). It is
   * never derived from the classes currently selected: doing that rescales the
   * drawing on every slider step, so the circles shift under the cursor exactly
   * when you are trying to compare one position against the next. Scaling to the
   * reachable extremes means the whole of IT5-IT7 fits at one fixed factor, at
   * every size.
   *
   * @param basic  diameter in mm
   * @param lo,hi  widest reachable deviations in um (from precisionExtremes)
   */
  function pinnedExaggeration(basic, lo, hi) {
    var e = clampExaggeration(basic, { upper: hi, lower: lo }, null, Infinity);
    if (!isFinite(e)) return 1;
    // Round to 2 significant figures so the label reads as a round number, then
    // step back below the geometric limit so rounding cannot push it over.
    var mag = Math.pow(10, Math.floor(Math.log(e) / Math.LN10) - 1);
    var rounded = Math.floor(e / mag) * mag;
    return Math.max(1, rounded);
  }

  /**
   * Largest factor that still draws inside the box for these particular classes.
   *
   * A pinned factor cannot be applied unconditionally: at 3 mm a U6 hole sits
   * 24 um below basic, and at high exaggeration that pushes the inner radius past
   * the centre and the circle turns inside out. So the pinned factor is used as-is
   * whenever it fits -- which is the whole normal working range -- and is reduced
   * only where geometry forces it. The label always reports the factor actually
   * used, so a reduction is visible rather than silent.
   */
  function clampExaggeration(basic, pin, hole, E) {
    var devs = [0];
    if (pin) devs.push(pin.upper, pin.lower);
    if (hole) devs.push(hole.upper, hole.lower);
    var lo = Math.min.apply(null, devs), hi = Math.max.apply(null, devs);
    var pxPerMmTrue = R0 / (basic / 2);
    var limit = E;
    if (lo < 0) {
      limit = Math.min(limit, (R0 - R_MIN) * 2000 / (pxPerMmTrue * -lo));
    }
    if (hi > 0) {
      limit = Math.min(limit, (R_MAX - R0) * 2000 / (pxPerMmTrue * hi));
    }
    return Math.max(1, limit);
  }

  /**
   * @param opts {basic, pin, hole, exaggeration}
   * pin/hole are ISO286.limits objects; either may be null.
   */
  function circleView(opts) {
    var basic = opts.basic, pin = opts.pin, hole = opts.hole;
    var E = opts.exaggeration || 1;
    var W = 400, H = 400, cx = W / 2, cy = H / 2;
    var rBasicMm = basic / 2;
    var pxPerMmTrue = R0 / rBasicMm;

    // Radial display position for a diametral deviation in um.
    function rp(devUm) {
      return R0 + pxPerMmTrue * E * (devUm / 2000);
    }

    var s = '<svg viewBox="0 0 ' + W + ' ' + H + '" class="viz-svg" ' +
            'role="img" aria-label="Concentric pin and hole tolerance bands">';

    // Basic-size reference circle.
    s += '<circle cx="' + cx + '" cy="' + cy + '" r="' + R0 + '" fill="none" ' +
         'stroke="currentColor" stroke-opacity="0.28" stroke-width="1" ' +
         'stroke-dasharray="3 4"/>';

    if (hole) s += ring(cx, cy, rp(hole.lower), rp(hole.upper), C.holeLight);
    if (pin)  s += ring(cx, cy, rp(pin.lower), rp(pin.upper), C.pinLight);

    // Where the two bands overlap, pin and hole can take the SAME diameter -- so
    // the fit could come out either way. Note this is the transition condition,
    // not "where interference happens": a guaranteed interference fit such as
    // H7/p6 has no overlap at all because the bands are fully separated.
    if (pin && hole) {
      var lo = Math.max(pin.lower, hole.lower), hi = Math.min(pin.upper, hole.upper);
      if (hi > lo) s += ring(cx, cy, rp(lo), rp(hi), C.overlap);
    }

    if (hole) {
      s += '<circle cx="' + cx + '" cy="' + cy + '" r="' + rp((hole.upper + hole.lower) / 2).toFixed(2) +
           '" fill="none" stroke="' + C.holeDark + '" stroke-width="2.2"/>';
    }
    if (pin) {
      s += '<circle cx="' + cx + '" cy="' + cy + '" r="' + rp((pin.upper + pin.lower) / 2).toFixed(2) +
           '" fill="none" stroke="' + C.pinDark + '" stroke-width="2.2"/>';
    }

    // Centre mark.
    s += '<path d="M' + (cx - 9) + ' ' + cy + 'h18M' + cx + ' ' + (cy - 9) + 'v18" ' +
         'stroke="currentColor" stroke-opacity="0.45" stroke-width="1"/>';

    // Scale warning, always visible.
    s += '<text x="' + cx + '" y="' + (H - 12) + '" text-anchor="middle" ' +
         'class="viz-warn">NOT TO SCALE — tolerance bands exaggerated ×' +
         Math.round(E) + '</text>';

    s += '</svg>';
    return s;
  }

  /** Tiny companion drawn at true scale, so the exaggeration stays in context. */
  function trueScaleView(opts) {
    var basic = opts.basic, pin = opts.pin, hole = opts.hole;
    var W = 120, H = 120, cx = 60, cy = 60, r0 = 44;
    var pxPerMm = r0 / (basic / 2);
    function rp(devUm) { return r0 + pxPerMm * (devUm / 2000); }
    var s = '<svg viewBox="0 0 ' + W + ' ' + H + '" class="viz-svg-mini" ' +
            'role="img" aria-label="The same fit drawn at true scale">';
    if (hole) s += ring(cx, cy, rp(hole.lower), rp(hole.upper), C.holeLight);
    if (pin)  s += ring(cx, cy, rp(pin.lower), rp(pin.upper), C.pinLight);
    if (hole) s += '<circle cx="' + cx + '" cy="' + cy + '" r="' + rp((hole.upper + hole.lower) / 2).toFixed(2) +
                   '" fill="none" stroke="' + C.holeDark + '" stroke-width="1.2"/>';
    if (pin)  s += '<circle cx="' + cx + '" cy="' + cy + '" r="' + rp((pin.upper + pin.lower) / 2).toFixed(2) +
                   '" fill="none" stroke="' + C.pinDark + '" stroke-width="1.2"/>';
    s += '</svg>';
    return s;
  }

  /* -------------------------------------------------- 2. tolerance zone diagram */

  /** The classic ISO zone chart: deviations in um about the zero (basic size) line. */
  function zoneChart(opts) {
    var pin = opts.pin, hole = opts.hole, basic = opts.basic;
    var W = 560, H = 320;
    var padL = 58, padR = 18, padT = 26, padB = 44;
    var plotW = W - padL - padR, plotH = H - padT - padB;

    var vals = [0];
    if (pin) vals.push(pin.upper, pin.lower);
    if (hole) vals.push(hole.upper, hole.lower);
    var lo = Math.min.apply(null, vals), hi = Math.max.apply(null, vals);
    var span = Math.max(hi - lo, 1);
    lo -= span * 0.18; hi += span * 0.18;

    function y(um) { return padT + plotH * (hi - um) / (hi - lo); }

    var s = '<svg viewBox="0 0 ' + W + ' ' + H + '" class="viz-svg" ' +
            'role="img" aria-label="Tolerance zone diagram in micrometres">';

    // Axis ticks at nice intervals.
    var tk = ticks(lo, hi, 6);
    tk.values.forEach(function (t) {
      var yy = y(t);
      s += '<line x1="' + padL + '" y1="' + yy.toFixed(1) + '" x2="' + (W - padR) +
           '" y2="' + yy.toFixed(1) + '" stroke="currentColor" stroke-opacity="' +
           (Math.abs(t) < tk.step / 100 ? '0' : '0.10') + '" stroke-width="1"/>';
      s += '<text x="' + (padL - 8) + '" y="' + (yy + 3.5).toFixed(1) +
           '" text-anchor="end" class="viz-tick">' + signed(t, tk.dp) + '</text>';
    });

    // Zero line = basic size.
    var y0 = y(0);
    s += '<line x1="' + padL + '" y1="' + y0.toFixed(1) + '" x2="' + (W - padR) +
         '" y2="' + y0.toFixed(1) + '" stroke="currentColor" stroke-opacity="0.75" ' +
         'stroke-width="1.5"/>';
    s += '<text x="' + (W - padR) + '" y="' + (y0 - 6).toFixed(1) +
         '" text-anchor="end" class="viz-tick">basic size ' + basic.toFixed(3) + ' mm</text>';
    s += '<text x="14" y="' + (padT + plotH / 2) + '" class="viz-axis" ' +
         'transform="rotate(-90 14 ' + (padT + plotH / 2) + ')" text-anchor="middle">' +
         'deviation (µm)</text>';

    var colW = plotW / 2;
    function zone(feature, i, dark, light, name) {
      if (!feature) return '';
      var bx = padL + i * colW + colW * 0.22;
      var bw = colW * 0.56;
      var yTop = y(feature.upper), yBot = y(feature.lower);
      var h = Math.max(yBot - yTop, 2);
      var out = '<rect x="' + bx.toFixed(1) + '" y="' + yTop.toFixed(1) + '" width="' +
                bw.toFixed(1) + '" height="' + h.toFixed(1) + '" fill="' + light +
                '" stroke="' + dark + '" stroke-width="1.6" rx="2"/>';
      // Mean line through the zone.
      var ym = y((feature.upper + feature.lower) / 2);
      out += '<line x1="' + bx.toFixed(1) + '" y1="' + ym.toFixed(1) + '" x2="' +
             (bx + bw).toFixed(1) + '" y2="' + ym.toFixed(1) + '" stroke="' + dark +
             '" stroke-width="2" stroke-dasharray="4 3"/>';
      out += '<text x="' + (bx + bw / 2).toFixed(1) + '" y="' + (H - 24) +
             '" text-anchor="middle" class="viz-label">' + esc(name) + '</text>';
      out += '<text x="' + (bx + bw / 2).toFixed(1) + '" y="' + (H - 10) +
             '" text-anchor="middle" class="viz-sub">' + signed(feature.upper, 0) +
             ' / ' + signed(feature.lower, 0) + ' µm</text>';
      return out;
    }
    s += zone(pin, 0, C.pinDark, C.pinLight, pin ? 'pin ' + pin.label : 'pin');
    s += zone(hole, 1, C.holeDark, C.holeLight, hole ? 'hole ' + hole.label : 'hole');

    s += '</svg>';
    return s;
  }

  /* ------------------------------------------------------------- 3. bell curve */

  /**
   * Normal distribution of interference from the RSS stackup, with the clearance
   * side shaded blue and the interference side red so the split at zero is the
   * first thing the eye lands on.
   */
  function bellCurve(stats) {
    var W = 700, H = 190;
    var padL = 48, padR = 18, padT = 20, padB = 40;
    var plotW = W - padL - padR, plotH = H - padT - padB;
    var wc = stats.worstCase;

    // Cover both the RSS tails and the worst-case limits, so the viewer can see
    // how much narrower the statistical prediction is.
    var lo = Math.min(stats.mean - 4 * stats.sigma, wc.min);
    var hi = Math.max(stats.mean + 4 * stats.sigma, wc.max);
    var pad = (hi - lo) * 0.10 || 1;
    lo -= pad; hi += pad;
    if (lo > 0) lo = -pad;          // always show the zero line
    if (hi < 0) hi = pad;

    function x(um) { return padL + plotW * (um - lo) / (hi - lo); }

    var peak = stats.sigma > 0 ? stats.pdf(stats.mean) : 1;
    function y(d) { return padT + plotH * (1 - d / peak); }

    var s = '<svg viewBox="0 0 ' + W + ' ' + H + '" class="viz-svg" ' +
            'role="img" aria-label="Predicted distribution of interference">';

    // Build the curve once, then reuse it for both shaded halves.
    var N = 240, pts = [];
    for (var i = 0; i <= N; i++) {
      var xv = lo + (hi - lo) * i / N;
      pts.push([xv, stats.pdf(xv)]);
    }
    function areaPath(from, to) {
      var seg = pts.filter(function (p) { return p[0] >= from && p[0] <= to; });
      if (!seg.length) return '';
      var d = 'M' + x(from).toFixed(1) + ' ' + y(0).toFixed(1);
      // Clamp the edges so the shaded region meets the baseline squarely.
      d += ' L' + x(from).toFixed(1) + ' ' + y(stats.pdf(from)).toFixed(1);
      seg.forEach(function (p) { d += ' L' + x(p[0]).toFixed(1) + ' ' + y(p[1]).toFixed(1); });
      d += ' L' + x(to).toFixed(1) + ' ' + y(stats.pdf(to)).toFixed(1);
      d += ' L' + x(to).toFixed(1) + ' ' + y(0).toFixed(1) + ' Z';
      return d;
    }

    var zeroClamped = Math.min(Math.max(0, lo), hi);
    s += '<path d="' + areaPath(lo, zeroClamped) + '" fill="' + C.holeLight + '"/>';
    s += '<path d="' + areaPath(zeroClamped, hi) + '" fill="' + C.pinLight + '"/>';

    // Curve outline.
    var line = pts.map(function (p, i) {
      return (i ? 'L' : 'M') + x(p[0]).toFixed(1) + ' ' + y(p[1]).toFixed(1);
    }).join(' ');
    s += '<path d="' + line + '" fill="none" stroke="currentColor" ' +
         'stroke-opacity="0.75" stroke-width="1.6"/>';

    // Baseline + axis.
    s += '<line x1="' + padL + '" y1="' + y(0).toFixed(1) + '" x2="' + (W - padR) +
         '" y2="' + y(0).toFixed(1) + '" stroke="currentColor" stroke-opacity="0.35"/>';

    var tk = ticks(lo, hi, 8);
    tk.values.forEach(function (t) {
      s += '<text x="' + x(t).toFixed(1) + '" y="' + (y(0) + 16).toFixed(1) +
           '" text-anchor="middle" class="viz-tick">' + signed(t, tk.dp) + '</text>';
    });
    s += '<text x="' + (padL + plotW / 2) + '" y="' + (H - 8) +
         '" text-anchor="middle" class="viz-axis">interference (µm) — ' +
         'negative is clearance</text>';

    // Zero line: the interference/clearance boundary.
    s += '<line x1="' + x(0).toFixed(1) + '" y1="' + padT + '" x2="' + x(0).toFixed(1) +
         '" y2="' + y(0).toFixed(1) + '" stroke="currentColor" stroke-width="1.6"/>';

    function marker(um, label, dash, opacity) {
      if (um < lo || um > hi) return '';
      return '<line x1="' + x(um).toFixed(1) + '" y1="' + (padT + 8) + '" x2="' +
             x(um).toFixed(1) + '" y2="' + y(0).toFixed(1) + '" stroke="currentColor" ' +
             'stroke-opacity="' + opacity + '" stroke-width="1.2" stroke-dasharray="' +
             dash + '"/>' +
             '<text x="' + x(um).toFixed(1) + '" y="' + (padT + 2) +
             '" text-anchor="middle" class="viz-tick">' + esc(label) + '</text>';
    }
    // Worst-case limits (what the drawing must survive) vs RSS limits.
    s += marker(wc.min, 'WC ' + signed(wc.min, 1), '2 3', '0.55');
    s += marker(wc.max, 'WC ' + signed(wc.max, 1), '2 3', '0.55');
    s += marker(stats.min, signed(stats.k, 0).replace('+', '') + 'σ', '5 3', '0.8');
    s += marker(stats.max, '+' + fmt(stats.k, 0) + 'σ', '5 3', '0.8');
    s += marker(stats.mean, 'mean ' + signed(stats.mean, 1), '', '0.95');

    // Percentages, placed in the middle of each shaded region.
    function pct(v) { 
      if (v >= 0.9999 && v < 1) return '>99.99%';
      if (v <= 0.0001 && v > 0) return '<0.01%';
      return (v * 100).toFixed(v > 0.001 && v < 0.999 ? 1 : 2) + '%';
    }
    if (stats.pClearance > 0.0005) {
      s += '<text x="' + ((padL + x(0)) / 2).toFixed(1) + '" y="' + (padT + plotH * 0.55) +
           '" text-anchor="middle" class="viz-pct viz-pct-hole">' +
           pct(stats.pClearance) + ' clearance</text>';
    }
    if (stats.pInterference > 0.0005) {
      s += '<text x="' + ((x(0) + W - padR) / 2).toFixed(1) + '" y="' + (padT + plotH * 0.38) +
           '" text-anchor="middle" class="viz-pct viz-pct-pin">' +
           pct(stats.pInterference) + ' interference</text>';
    }

    s += '</svg>';
    return s;
  }

  return {
    circleView: circleView,
    trueScaleView: trueScaleView,
    zoneChart: zoneChart,
    bellCurve: bellCurve,
    pinnedExaggeration: pinnedExaggeration,
    clampExaggeration: clampExaggeration,
    fmt: fmt,
    signed: signed,
    COLORS: C
  };
})();
